export const CASE_STATUSES = {
  OPEN: 'OPEN',
  INVESTIGATING: 'INVESTIGATING',
  DECIDING: 'DECIDING',
  ACTION_IN_PROGRESS: 'ACTION_IN_PROGRESS',
  OBSERVING: 'OBSERVING',
  REPLANNING: 'REPLANNING',
  VERIFYING: 'VERIFYING',
  RESOLVED: 'RESOLVED',
  ESCALATED: 'ESCALATED'
};

export const AGENT_EVENT_TYPES = {
  GOAL_RECEIVED: 'GOAL_RECEIVED',
  INVESTIGATION: 'INVESTIGATION',
  TOOL_SELECTION: 'TOOL_SELECTION',
  TOOL_EXECUTION: 'TOOL_EXECUTION',
  DECISION: 'DECISION',
  ACTION_STARTED: 'ACTION_STARTED',
  ACTION_RESULT: 'ACTION_RESULT',
  FAILURE: 'FAILURE',
  OBSERVATION: 'OBSERVATION',
  REPLAN: 'REPLAN',
  VERIFICATION: 'VERIFICATION',
  ESCALATION: 'ESCALATION',
  RESOLUTION: 'RESOLUTION'
};
