module.exports = {
  CASE_STATUSES: {
    OPEN: 'OPEN',
    INVESTIGATING: 'INVESTIGATING',
    DECIDING: 'DECIDING',
    ACTION_IN_PROGRESS: 'ACTION_IN_PROGRESS',
    OBSERVING: 'OBSERVING',
    REPLANNING: 'REPLANNING',
    VERIFYING: 'VERIFYING',
    RESOLVED: 'RESOLVED',
    ESCALATED: 'ESCALATED'
  },
  AGENT_EVENT_TYPES: {
    GOAL_RECEIVED: 'GOAL_RECEIVED',
    INVESTIGATION: 'INVESTIGATION',
    TOOL_SELECTION: 'TOOL_SELECTION',
    TOOL_EXECUTION: 'TOOL_EXECUTION',
    DECISION: 'DECISION',
    ACTION_STARTED: 'ACTION_STARTED',
    ACTION_RESULT: 'ACTION_RESULT',
    FAILURE: 'FAILURE',
    OBSERVATION: 'OBSERVATION',
    REPLAN: 'REPLAN',
    VERIFICATION: 'VERIFICATION',
    ESCALATION: 'ESCALATION',
    RESOLUTION: 'RESOLUTION'
  },
  ACTION_TYPES: {
    REFUND: 'REFUND',
    REPLACEMENT: 'REPLACEMENT',
    CANCELLATION: 'CANCELLATION'
  },
  ERROR_CODES: {
    INVALID_INPUT: 'INVALID_INPUT',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    STATE_CONFLICT: 'STATE_CONFLICT',
    INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
    POLICY_VIOLATION: 'POLICY_VIOLATION',
    TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
  }
};
